version: '3.0'
services:
  dynamodb: 
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-southeast-1
  app-node:
   depends_on:
     - dynamodb
   image: amazon/aws-cli
   container_name: app-node
   ports:
    - "8080:8080"
   environment:
     AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
     AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
     AWS_REGION: 'ap-southeast-1'
   command:
     dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region ap-southeast-1
